// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGH3TjeJdYdgTTO19HFqhJ_7d-J9HEEmc',
    appId: '1:87307917282:web:f991b466e34d40fdc94bbb',
    messagingSenderId: '87307917282',
    projectId: 'flutter-todo-a9a5b',
    authDomain: 'flutter-todo-a9a5b.firebaseapp.com',
    storageBucket: 'flutter-todo-a9a5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWDFhndmoVWQkZgCamY3lMZpG2BtPIF8',
    appId: '1:87307917282:android:bba243ff9f99e63bc94bbb',
    messagingSenderId: '87307917282',
    projectId: 'flutter-todo-a9a5b',
    storageBucket: 'flutter-todo-a9a5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwJoVrxkUVea_9SYgaQqmvuh3A-EO0XfE',
    appId: '1:87307917282:ios:0f7e1e36e02e2969c94bbb',
    messagingSenderId: '87307917282',
    projectId: 'flutter-todo-a9a5b',
    storageBucket: 'flutter-todo-a9a5b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwJoVrxkUVea_9SYgaQqmvuh3A-EO0XfE',
    appId: '1:87307917282:ios:0f7e1e36e02e2969c94bbb',
    messagingSenderId: '87307917282',
    projectId: 'flutter-todo-a9a5b',
    storageBucket: 'flutter-todo-a9a5b.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGH3TjeJdYdgTTO19HFqhJ_7d-J9HEEmc',
    appId: '1:87307917282:web:4d45b6f8137e13e6c94bbb',
    messagingSenderId: '87307917282',
    projectId: 'flutter-todo-a9a5b',
    authDomain: 'flutter-todo-a9a5b.firebaseapp.com',
    storageBucket: 'flutter-todo-a9a5b.appspot.com',
  );

}